[{"restaurant"=>
   {"R"=>{"res_id"=>16718128},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718128",
    "name"=>"Pink Door",
    "url"=>"https://www.zomato.com/seattle/pink-door-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"Pike Place Market, 1919 Post Alley, Seattle 98101",
      "locality"=>"Pike Place Market",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6102890000",
      "longitude"=>"-122.3426586000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Pike Place Market, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Italian",
    "average_cost_for_two"=>100,
    "price_range"=>4,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718128_RESTAURANT_50bfc6f5464b1ff9b575c9b92da1106d_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.6", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1636", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/pink-door-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/pink-door-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718128_RESTAURANT_50bfc6f5464b1ff9b575c9b92da1106d_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718128",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/pink-door-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16720700},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16720700",
    "name"=>"Serious Pie",
    "url"=>"https://www.zomato.com/seattle/serious-pie-belltown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"316 Virginia Street, Seattle 98101",
      "locality"=>"Belltown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6128967000",
      "longitude"=>"-122.3405801000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Belltown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Pizza, Italian",
    "average_cost_for_two"=>40,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16720700_RESTAURANT_8f88237d6da8d97c522a045f965775e8_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.4", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"1417", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/serious-pie-belltown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/serious-pie-belltown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16720700_RESTAURANT_8f88237d6da8d97c522a045f965775e8_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16720700",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/serious-pie-belltown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16720781},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16720781",
    "name"=>"Steelhead Diner",
    "url"=>"https://www.zomato.com/seattle/steelhead-diner-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"95 Pine Street 98101",
      "locality"=>"Pike Place Market",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6095486000",
      "longitude"=>"-122.3411817000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Pike Place Market, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Fish and Chips, Seafood, Pacific Northwest",
    "average_cost_for_two"=>45,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16720781_RESTAURANT_359f705c9bd6ec34b1e8868bf01b1708_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.2", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"835", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/steelhead-diner-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/steelhead-diner-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16720781_RESTAURANT_359f705c9bd6ec34b1e8868bf01b1708_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16720781",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/steelhead-diner-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16717959},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16717959",
    "name"=>"Umi Sake House",
    "url"=>"https://www.zomato.com/seattle/umi-sake-house-belltown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"2230 1st Avenue 98121",
      "locality"=>"Belltown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6133919000",
      "longitude"=>"-122.3459702000",
      "zipcode"=>"98121",
      "country_id"=>216,
      "locality_verbose"=>"Belltown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Sushi, Japanese",
    "average_cost_for_two"=>75,
    "price_range"=>3,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16717959_RESTAURANT_cfc8f3c4b6e21de9b6a80373e126ea68_c.JPG?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.4", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"789", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/umi-sake-house-belltown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/umi-sake-house-belltown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16717959_RESTAURANT_cfc8f3c4b6e21de9b6a80373e126ea68_c.JPG",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16717959",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/umi-sake-house-belltown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718159},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718159",
    "name"=>"Macrina Bakery",
    "url"=>"https://www.zomato.com/seattle/macrina-bakery-belltown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"2408 1st Avenue, Seattle 98121",
      "locality"=>"Belltown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6144973000",
      "longitude"=>"-122.3480069000",
      "zipcode"=>"98121",
      "country_id"=>216,
      "locality_verbose"=>"Belltown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Cafe, Bakery",
    "average_cost_for_two"=>35,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718159_RESTAURANT_22b16975969967e50b94d87da76a2d36.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.4", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"790", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/macrina-bakery-belltown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/macrina-bakery-belltown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718159_RESTAURANT_22b16975969967e50b94d87da76a2d36.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718159",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/macrina-bakery-belltown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718098},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718098",
    "name"=>"Piroshky Piroshky",
    "url"=>"https://www.zomato.com/seattle/piroshky-piroshky-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"Pike Place Market, 1908 Pike Place, Seattle 98101",
      "locality"=>"Pike Place Market",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6100152000",
      "longitude"=>"-122.3423898000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Pike Place Market, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Russian, Bakery",
    "average_cost_for_two"=>15,
    "price_range"=>1,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718098_RESTAURANT_2f458fe25e0a0da00ed0a8629c22f186.JPG?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.5", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"869", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/piroshky-piroshky-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/piroshky-piroshky-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718098_RESTAURANT_2f458fe25e0a0da00ed0a8629c22f186.JPG",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718098",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/piroshky-piroshky-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718687},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718687",
    "name"=>"Wild Ginger",
    "url"=>"https://www.zomato.com/seattle/wild-ginger-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"1401 3rd Avenue 98101",
      "locality"=>"Downtown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6088914000",
      "longitude"=>"-122.3373437000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Downtown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Vietnamese, Chinese, Asian",
    "average_cost_for_two"=>75,
    "price_range"=>3,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718687_RESTAURANT_b25bc478f507ad301a07023ac4e41c3c_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.4", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"1896", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/wild-ginger-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/wild-ginger-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718687_RESTAURANT_b25bc478f507ad301a07023ac4e41c3c_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718687",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/wild-ginger-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718734},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718734",
    "name"=>"Metropolitan Grill",
    "url"=>"https://www.zomato.com/seattle/metropolitan-grill-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"820 2nd Avenue 98104",
      "locality"=>"Downtown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6039300000",
      "longitude"=>"-122.3338900000",
      "zipcode"=>"98104",
      "country_id"=>216,
      "locality_verbose"=>"Downtown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Steak, American",
    "average_cost_for_two"=>95,
    "price_range"=>3,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"",
    "user_rating"=>{"aggregate_rating"=>"4.3", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"1106", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/metropolitan-grill-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/metropolitan-grill-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718734",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/metropolitan-grill-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16719173},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16719173",
    "name"=>"Top Pot Doughnuts",
    "url"=>"https://www.zomato.com/seattle/top-pot-doughnuts-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"2124 5th Avenue, Seattle 98121",
      "locality"=>"Downtown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6152360000",
      "longitude"=>"-122.3411210000",
      "zipcode"=>"98121",
      "country_id"=>216,
      "locality_verbose"=>"Downtown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Donuts, Coffee and Tea",
    "average_cost_for_two"=>15,
    "price_range"=>1,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16719173_RESTAURANT_da292c2a68a300db613188b20f023aa5_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.3", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"838", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/top-pot-doughnuts-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/top-pot-doughnuts-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16719173_RESTAURANT_da292c2a68a300db613188b20f023aa5_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16719173",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/top-pot-doughnuts-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16719032},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16719032",
    "name"=>"Honey Hole",
    "url"=>"https://www.zomato.com/seattle/honey-hole-capitol-hill?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"703 East Pike Street, Seattle 98122",
      "locality"=>"Capitol Hill",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6139833333",
      "longitude"=>"-122.3233111111",
      "zipcode"=>"98122",
      "country_id"=>216,
      "locality_verbose"=>"Capitol Hill, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Sandwich",
    "average_cost_for_two"=>30,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16719032_RESTAURANT_0fd1f2678ea71dd049ee2aa7639fe665_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.7", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1023", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/honey-hole-capitol-hill/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/honey-hole-capitol-hill/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16719032_RESTAURANT_0fd1f2678ea71dd049ee2aa7639fe665_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16719032",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/honey-hole-capitol-hill/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718204},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718204",
    "name"=>"Matt's in the Market",
    "url"=>"https://www.zomato.com/seattle/matts-in-the-market-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"Pike Place Market, 94 Pike Street, Seattle 98101",
      "locality"=>"Pike Place Market",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6089276000",
      "longitude"=>"-122.3404449000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Pike Place Market, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Pacific Northwest, Seafood",
    "average_cost_for_two"=>55,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718204_RESTAURANT_2684b0182576165f5bb10167ad9c38fc.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.2", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"894", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/matts-in-the-market-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/matts-in-the-market-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718204_RESTAURANT_2684b0182576165f5bb10167ad9c38fc.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718204",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/matts-in-the-market-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718075},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718075",
    "name"=>"Lola",
    "url"=>"https://www.zomato.com/seattle/lola-belltown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"Hotel Andra, 2000 4th Avenue, Seattle 98121",
      "locality"=>"Hotel Andra",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6130722222",
      "longitude"=>"-122.3398222222",
      "zipcode"=>"98121",
      "country_id"=>216,
      "locality_verbose"=>"Hotel Andra, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Greek, Mediterranean, Pacific Northwest",
    "average_cost_for_two"=>70,
    "price_range"=>3,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718075_RESTAURANT_33e9a5535b2cf394314ac369149688cd.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.4", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"1313", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/lola-belltown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/lola-belltown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718075_RESTAURANT_33e9a5535b2cf394314ac369149688cd.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718075",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/lola-belltown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16727499},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16727499",
    "name"=>"Toulouse Petit Kitchen & Lounge",
    "url"=>"https://www.zomato.com/seattle/toulouse-petit-kitchen-lounge-queen-anne-lower?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"601 Queen Anne Avenue North 98109",
      "locality"=>"Queen Anne: Lower",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6251800000",
      "longitude"=>"-122.3567900000",
      "zipcode"=>"98109",
      "country_id"=>216,
      "locality_verbose"=>"Queen Anne: Lower, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Cajun, French",
    "average_cost_for_two"=>80,
    "price_range"=>3,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16727499_RESTAURANT_49bc897ed4b5bc80f7fc89f362c554ae.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.8", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1426", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/toulouse-petit-kitchen-lounge-queen-anne-lower/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/toulouse-petit-kitchen-lounge-queen-anne-lower/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16727499_RESTAURANT_49bc897ed4b5bc80f7fc89f362c554ae.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16727499",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/toulouse-petit-kitchen-lounge-queen-anne-lower/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16717368},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16717368",
    "name"=>"Canlis",
    "url"=>"https://www.zomato.com/seattle/canlis-westlake?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"2576 Aurora Avenue North, Seattle 98109",
      "locality"=>"Westlake",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6429138889",
      "longitude"=>"-122.3468250000",
      "zipcode"=>"98109",
      "country_id"=>216,
      "locality_verbose"=>"Westlake, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Pacific Northwest, New American",
    "average_cost_for_two"=>150,
    "price_range"=>4,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16717368_RESTAURANT_628abe40776fdf7c0cf18baedf3af905_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.2", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"909", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/canlis-westlake/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/canlis-westlake/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16717368_RESTAURANT_628abe40776fdf7c0cf18baedf3af905_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16717368",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/canlis-westlake/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16720729},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16720729",
    "name"=>"Purple Cafe and Wine Bar",
    "url"=>"https://www.zomato.com/seattle/purple-cafe-and-wine-bar-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"1225 4th Avenue, Seattle 98101",
      "locality"=>"Downtown",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6079958000",
      "longitude"=>"-122.3349899000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Downtown, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Pacific Northwest, American",
    "average_cost_for_two"=>80,
    "price_range"=>3,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16720729_RESTAURANT_64e10a985b07adbffe9f1809bcafafd5.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.2", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"995", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/purple-cafe-and-wine-bar-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/purple-cafe-and-wine-bar-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16720729_RESTAURANT_64e10a985b07adbffe9f1809bcafafd5.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16720729",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/purple-cafe-and-wine-bar-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16719415},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16719415",
    "name"=>"La Carta de Oaxaca",
    "url"=>"https://www.zomato.com/seattle/la-carta-de-oaxaca-ballard?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"5431 Ballard Avenue NW, Seattle 98107",
      "locality"=>"Ballard",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6680532000",
      "longitude"=>"-122.3858915000",
      "zipcode"=>"98107",
      "country_id"=>216,
      "locality_verbose"=>"Ballard, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Mexican",
    "average_cost_for_two"=>35,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16719415_RESTAURANT_7e1c8a6454380195510bef89fb6a37d3_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.7", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1429", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/la-carta-de-oaxaca-ballard/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/la-carta-de-oaxaca-ballard/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16719415_RESTAURANT_7e1c8a6454380195510bef89fb6a37d3_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16719415",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/la-carta-de-oaxaca-ballard/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16720764},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16720764",
    "name"=>"Bakery Nouveau",
    "url"=>"https://www.zomato.com/seattle/bakery-nouveau-west-seattle?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"4737 California Avenue SW, Seattle 98116",
      "locality"=>"West Seattle",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.5603980000",
      "longitude"=>"-122.3870410000",
      "zipcode"=>"98116",
      "country_id"=>216,
      "locality_verbose"=>"West Seattle, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Bakery, French, Desserts",
    "average_cost_for_two"=>15,
    "price_range"=>1,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16720764_RESTAURANT_2408ef7591976c70e4a34e451451685c_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.9", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1009", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/bakery-nouveau-west-seattle/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>
     "https://www.zomato.com/seattle/bakery-nouveau-west-seattle/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16720764_RESTAURANT_2408ef7591976c70e4a34e451451685c_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16720764",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/bakery-nouveau-west-seattle/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16717268},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16717268",
    "name"=>"Le Pichet",
    "url"=>"https://www.zomato.com/seattle/le-pichet-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"Pike Place Market, 1933 1st Avenue, Seattle 98101",
      "locality"=>"Pike Place Market",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6107440000",
      "longitude"=>"-122.3426690000",
      "zipcode"=>"98101",
      "country_id"=>216,
      "locality_verbose"=>"Pike Place Market, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Cafe, French",
    "average_cost_for_two"=>50,
    "price_range"=>2,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16717268_RESTAURANT_297d6a1a9a3343ab247f83ab9e91c918_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.5", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1116", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/le-pichet-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/le-pichet-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16717268_RESTAURANT_297d6a1a9a3343ab247f83ab9e91c918_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16717268",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/le-pichet-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16719511},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16719511",
    "name"=>"Ray's Boathouse",
    "url"=>"https://www.zomato.com/seattle/rays-boathouse-ballard?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"6049 Seaview Avenue NW, Seattle 98107",
      "locality"=>"Ballard",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6733777778",
      "longitude"=>"-122.4073777778",
      "zipcode"=>"98107",
      "country_id"=>216,
      "locality_verbose"=>"Ballard, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Pacific Northwest, Seafood",
    "average_cost_for_two"=>130,
    "price_range"=>4,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16719511_RESTAURANT_b93892ad5ad581e5f6d17a61d8ba6235_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.1", "rating_text"=>"Very Good", "rating_color"=>"5BA829", "votes"=>"1412", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/rays-boathouse-ballard/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/rays-boathouse-ballard/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16719511_RESTAURANT_b93892ad5ad581e5f6d17a61d8ba6235_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16719511",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/rays-boathouse-ballard/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}},
 {"restaurant"=>
   {"R"=>{"res_id"=>16718458},
    "apikey"=>"4e444090a6cc15f3ea6a678736291ab3",
    "id"=>"16718458",
    "name"=>"Paseo",
    "url"=>"https://www.zomato.com/seattle/paseo-fremont?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "location"=>
     {"address"=>"4225 Fremont Avenue N, Seattle 98103",
      "locality"=>"Fremont",
      "city"=>"Seattle",
      "city_id"=>279,
      "latitude"=>"47.6585111111",
      "longitude"=>"-122.3499611111",
      "zipcode"=>"98103",
      "country_id"=>216,
      "locality_verbose"=>"Fremont, Seattle"},
    "switch_to_order_menu"=>0,
    "cuisines"=>"Caribbean, Sandwich, Cuban",
    "average_cost_for_two"=>25,
    "price_range"=>1,
    "currency"=>"$",
    "offers"=>[],
    "opentable_support"=>0,
    "is_zomato_book_res"=>0,
    "mezzo_provider"=>"OTHER",
    "is_book_form_web_view"=>0,
    "book_form_web_view_url"=>"",
    "book_again_url"=>"",
    "thumb"=>"https://b.zmtcdn.com/data/res_imagery/16718458_RESTAURANT_8d88c41b8b10f8d4ed8b9ea5ebeaadab_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
    "user_rating"=>{"aggregate_rating"=>"4.9", "rating_text"=>"Excellent", "rating_color"=>"3F7E00", "votes"=>"1773", "has_fake_reviews"=>0},
    "photos_url"=>"https://www.zomato.com/seattle/paseo-fremont/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
    "menu_url"=>"https://www.zomato.com/seattle/paseo-fremont/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
    "featured_image"=>"https://b.zmtcdn.com/data/res_imagery/16718458_RESTAURANT_8d88c41b8b10f8d4ed8b9ea5ebeaadab_c.jpg",
    "has_online_delivery"=>0,
    "is_delivering_now"=>0,
    "has_fake_reviews"=>0,
    "include_bogo_offers"=>true,
    "deeplink"=>"zomato://restaurant/16718458",
    "is_table_reservation_supported"=>0,
    "has_table_booking"=>0,
    "events_url"=>"https://www.zomato.com/seattle/paseo-fremont/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
    "establishment_types"=>[]}}]
